// Mocks generated by Mockito 5.4.4 from annotations
// in sigma/test/dosen_request_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sigma/data/models/schedule_request_model.dart' as _i4;
import 'package:sigma/data/services/dosen_request_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [DosenRequestService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDosenRequestService extends _i1.Mock
    implements _i2.DosenRequestService {
  MockDosenRequestService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<Map<String, dynamic>>> getMySchedules(String? kodeDosen) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMySchedules,
          [kodeDosen],
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<List<String>> getAllRuangan() => (super.noSuchMethod(
        Invocation.method(
          #getAllRuangan,
          [],
        ),
        returnValue: _i3.Future<List<String>>.value(<String>[]),
      ) as _i3.Future<List<String>>);

  @override
  _i3.Future<List<String>> getRuanganTersedia({
    required String? hari,
    required String? jamMulai,
    required String? jamSelesai,
    String? excludeScheduleId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRuanganTersedia,
          [],
          {
            #hari: hari,
            #jamMulai: jamMulai,
            #jamSelesai: jamSelesai,
            #excludeScheduleId: excludeScheduleId,
          },
        ),
        returnValue: _i3.Future<List<String>>.value(<String>[]),
      ) as _i3.Future<List<String>>);

  @override
  _i3.Future<bool> submitRequest({
    required String? idSchedule,
    required String? idDosen,
    required String? namaDosen,
    required String? tipeRequest,
    required Map<String, dynamic>? detailPerubahan,
    required String? alasan,
    required String? namaMatkul,
    required Map<String, dynamic>? jadwalLama,
    bool? isLate = false,
    String? idPeriodeRevisi,
    required String? offlineId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #submitRequest,
          [],
          {
            #idSchedule: idSchedule,
            #idDosen: idDosen,
            #namaDosen: namaDosen,
            #tipeRequest: tipeRequest,
            #detailPerubahan: detailPerubahan,
            #alasan: alasan,
            #namaMatkul: namaMatkul,
            #jadwalLama: jadwalLama,
            #isLate: isLate,
            #idPeriodeRevisi: idPeriodeRevisi,
            #offlineId: offlineId,
          },
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<List<_i4.ScheduleRequestModel>> getMyRequests(String? idDosen) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMyRequests,
          [idDosen],
        ),
        returnValue: _i3.Future<List<_i4.ScheduleRequestModel>>.value(
            <_i4.ScheduleRequestModel>[]),
      ) as _i3.Future<List<_i4.ScheduleRequestModel>>);

  @override
  _i3.Future<bool> cancelRequest(String? requestId) => (super.noSuchMethod(
        Invocation.method(
          #cancelRequest,
          [requestId],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
