// Mocks generated by Mockito 5.4.4 from annotations
// in sigma/test/schedule_request_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sigma/data/models/schedule_request_model.dart' as _i4;
import 'package:sigma/data/services/schedule_request_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ScheduleRequestService].
///
/// See the documentation for Mockito's code generation for more information.
class MockScheduleRequestService extends _i1.Mock
    implements _i2.ScheduleRequestService {
  MockScheduleRequestService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.ScheduleRequestModel>> getRequests({
    required String? idJurusan,
    String? status,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRequests,
          [],
          {
            #idJurusan: idJurusan,
            #status: status,
          },
        ),
        returnValue: _i3.Future<List<_i4.ScheduleRequestModel>>.value(
            <_i4.ScheduleRequestModel>[]),
      ) as _i3.Future<List<_i4.ScheduleRequestModel>>);

  @override
  _i3.Future<_i4.ScheduleRequestModel?> getRequestById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRequestById,
          [id],
        ),
        returnValue: _i3.Future<_i4.ScheduleRequestModel?>.value(),
      ) as _i3.Future<_i4.ScheduleRequestModel?>);

  @override
  _i3.Future<Map<String, int>> getStats(String? idJurusan) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStats,
          [idJurusan],
        ),
        returnValue: _i3.Future<Map<String, int>>.value(<String, int>{}),
      ) as _i3.Future<Map<String, int>>);

  @override
  _i3.Future<bool> approveRequest({
    required String? requestId,
    required String? processorId,
    String? catatanAdmin,
    required _i4.ScheduleRequestModel? request,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #approveRequest,
          [],
          {
            #requestId: requestId,
            #processorId: processorId,
            #catatanAdmin: catatanAdmin,
            #request: request,
          },
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> rejectRequest({
    required String? requestId,
    required String? processorId,
    required String? catatanAdmin,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #rejectRequest,
          [],
          {
            #requestId: requestId,
            #processorId: processorId,
            #catatanAdmin: catatanAdmin,
          },
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<int> flushQueue() => (super.noSuchMethod(
        Invocation.method(
          #flushQueue,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);
}
