// Mocks generated by Mockito 5.4.4 from annotations
// in sigma/test/schedule_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sigma/data/services/schedule_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ScheduleService].
///
/// See the documentation for Mockito's code generation for more information.
class MockScheduleService extends _i1.Mock implements _i2.ScheduleService {
  MockScheduleService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<Map<String, dynamic>>> getSchedules([String? filter = r'']) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSchedules,
          [filter],
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getSchedulesByKodeDosen(
          String? kodeDosen) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSchedulesByKodeDosen,
          [kodeDosen],
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<List<String>> getRuanganTersedia({
    required String? hari,
    required String? jamMulai,
    required String? jamSelesai,
    String? excludeScheduleId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRuanganTersedia,
          [],
          {
            #hari: hari,
            #jamMulai: jamMulai,
            #jamSelesai: jamSelesai,
            #excludeScheduleId: excludeScheduleId,
          },
        ),
        returnValue: _i3.Future<List<String>>.value(<String>[]),
      ) as _i3.Future<List<String>>);
}
