// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm6ZZ4106UV9SaCUlJdn4OPmkKhX0Vk8M',
    appId: '1:985832886043:web:33a8d42c9463f0fe1b8dbe',
    messagingSenderId: '985832886043',
    projectId: 'sigma-52c03',
    authDomain: 'sigma-52c03.firebaseapp.com',
    storageBucket: 'sigma-52c03.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQsvyi9QB2mDy-MPTa7vSMABuWA-cG8Hw',
    appId: '1:985832886043:android:29748d647943f8fc1b8dbe',
    messagingSenderId: '985832886043',
    projectId: 'sigma-52c03',
    storageBucket: 'sigma-52c03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSN8xr6ZT8QXbTDN26UYuu-7cMjKkvMm8',
    appId: '1:985832886043:ios:34285eec568549e81b8dbe',
    messagingSenderId: '985832886043',
    projectId: 'sigma-52c03',
    storageBucket: 'sigma-52c03.firebasestorage.app',
    iosBundleId: 'com.example.kampusKu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSN8xr6ZT8QXbTDN26UYuu-7cMjKkvMm8',
    appId: '1:985832886043:ios:34285eec568549e81b8dbe',
    messagingSenderId: '985832886043',
    projectId: 'sigma-52c03',
    storageBucket: 'sigma-52c03.firebasestorage.app',
    iosBundleId: 'com.example.kampusKu',
  );
}
